### PR TITLE
Refactor to use `logging` package rather than print(x).

### PR DESCRIPTION
**Pull request by NotNotQuinn**
I am making a cli program with camino, and these are some things that I added to make the cli experience better:
 - ~~`print(x)` statements from camino now start with `"[camino] "`~~
 - ~~`Arduino` constructor now takes optional `silent=False` argument~~
 - `print(x)` statements now use `logging.info/debug/warning/etc`
 
These might be personal preference, but I think they are good additions.

### CODE REVIEW

**Comment by n-wach** [comment]
Yes, good additions. Although honestly it would probably be best to switch from `print` statements to a module-level `Logger`:

At the top of `__init__.py`, add
```
import logging
logger = logging.getLogger(__name__)
```
and replace the `print` statements with `logger.debug/info/warning/etc` as you see fit. By default, only warnings and higher will be shown, but a user can always call `logging.getLogger("camino").setLevel()` if they need.

I think this would be better, as long as you don't need to silence logging on a per-Arduino basis.

**Comment by NotNotQuinn** [comment]
This does seem like a better approach. It seems like a quick change, I'll see if I can get to it tomorrow.

**Comment by NotNotQuinn** [comment]
I included each Arduino's address in the logs to help with debugging multiple Arduino. Otherwise I think this is good.

**Review by n-wach — APPROVED** [review]

**Comment by n-wach** [comment]
Looks great, thanks so much! I'll push an update shortly.

**Pull request merged**
